export * from './movies/Movies'
export * from './movie/Movie'
export * from './header/Header'
export * from './home/Home'
export * from './notFoundPage/NotFoundPage'
export * from './tvShow/TvShow'
export * from './tvShow/TvShow'
export * from './searchWindow/SearchWindow'